EMPLOYMENT_EMPLOYED = "employed"
EMPLOYMENT_SELF_EMPLOYED = "self_employed"
EMPLOYMENT_UNEMPLOYED = "unemployed"
EMPLOYMENT_RETIRED = "retired"

VALID_EMPLOYMENT_STATUSES = [
    EMPLOYMENT_EMPLOYED,
    EMPLOYMENT_SELF_EMPLOYED,
    EMPLOYMENT_UNEMPLOYED,
    EMPLOYMENT_RETIRED,
]
