APPROVAL_RISK_SCORE = 70
REJECTION_RISK_SCORE = 30
MIN_INCOME_TO_LOAN_RATIO = 2.0

# Risk score expectations used in tests.
# Each expectation is either one range tuple or multiple valid range tuples.
RISK_SCORE_APPROVED = (APPROVAL_RISK_SCORE, 100, True)  # 70 <= x <= 100
RISK_SCORE_REJECTED = (0, REJECTION_RISK_SCORE, False)  # 0  <= x <  30
RISK_SCORE_PENDING = (
    (REJECTION_RISK_SCORE, APPROVAL_RISK_SCORE, False),  # 30 <= x < 70
    (APPROVAL_RISK_SCORE, 100, True),  # 70 <= x <= 100 when ratio < 2.0
)

UNEMPLOYED_MAX_LOAN = 10000.00
MIN_LOAN_AMOUNT = 1000.00
MAX_LOAN_AMOUNT = 500000.00

MIN_APPLICANT_NAME_LENGTH = 1
MAX_APPLICANT_NAME_LENGTH = 100

MAX_NOTES_LENGTH = 500

IDEMPOTENCY_WINDOW_SECONDS = 60
API_TIMEOUT_SECONDS = 5
